-- Documents module — canonical schema mirror.
--
-- This file mirrors what is actually deployed in Supabase project
-- qqcljfqkrslwqakjjrvw (ap-south-1). The Documents module is part of
-- PracticeIQ; the `dociq_*` codename was retired in favour of `practiceiq_*`
-- prefixes for consistency with the rest of the PracticeIQ surface.
--
-- Authoritative source: Supabase MCP migration `workflowiq_schema_v1_drop_and_rebuild`.
-- Do NOT re-run this file on the live project — it is reference only.
--
-- Core PracticeIQ tables consumed by this service:
--   practiceiq_clients              — the CA's client roster (with telegram_* fields)
--   practiceiq_documents            — document storage metadata + ocr_text + embedding
--   practiceiq_messages             — bot conversation log (was dociq_messages)
--   practiceiq_document_checklist   — what to collect per client × period
--   practiceiq_document_status      — pending / received / overdue per (client, doc_type)
--   practiceiq_followup_log         — every reminder Shalini sent
--   practiceiq_settings             — firm config including ca_telegram_chat_id
--
-- RPCs:
--   hybrid_search(p_client_id, p_query_text, p_query_embedding, p_doc_type?, p_period?, p_match_count=5)
--     — RRF over practiceiq_messages (vector + FTS)
--   documents_hybrid_search(p_owner_user_id, p_query_text, p_query_embedding, p_client_id?, p_doc_type?, p_period?, p_match_count=5)
--     — RRF over practiceiq_documents.ocr_text
--
-- Storage bucket: `practiceiq-docs`
--   Path: {owner_user_id}/{client_id}/{filing_period}/{doc_type}/{ts}_{filename}
--
-- For the actual table DDL, see the migrations in the Supabase project. The
-- canonical mirror lives in `~/.claude/plans/check-the-current-supabase-unified-toast.md`
-- and the migration files applied via the Supabase MCP.

-- Quick reference of expected indexes (mirrors deployed state):
--   practiceiq_messages_client_time_idx    — (client_id, timestamp DESC)
--   practiceiq_messages_embedding_hnsw     — HNSW vector_cosine_ops
--   practiceiq_messages_fts_idx            — GIN to_tsvector('english', raw_text)
--   practiceiq_documents_client_period_idx — (client_id, filing_period)
--   practiceiq_documents_doc_period_idx    — (doc_type, filing_period)
--   practiceiq_documents_status_live_idx   — (status) WHERE deleted_at IS NULL
--   practiceiq_documents_embedding_hnsw    — HNSW vector_cosine_ops
--   practiceiq_documents_fts_idx           — GIN to_tsvector('english', ocr_text || ' ' || filename)
