'use client';

import { useMemo } from 'react';
import ReportLayout, { useMIS } from '../ReportLayout';
import { CHART_COLORS, SectionPanel } from '../atoms';
import { ALL_MIS_METRICS } from '@/lib/layer2/mis/metrics';

export default function MISReportCover() {
  return (
    <ReportLayout hideExcel={false}>
      <CoverContent />
    </ReportLayout>
  );
}

function CoverContent() {
  const { out, company, period, sector, navigateTo, navigateToModule } = useMIS();
  const counts = useMemo(() => {
    const c = { auto: 0, partial: 0, manual: 0, 'new-xml': 0 } as Record<string, number>;
    for (const m of ALL_MIS_METRICS) c[m.defaultStatus]++;
    return c;
  }, []);

  // Books L1 score lives in Account Health — jump module + view.
  const goToBooks = () => {
    navigateToModule('accounting');
    navigateTo('dashboard');
  };
  // Readiness % + MIS Score break down on the Analysis view.
  const goToAnalysis = () => navigateTo('mis-analysis');

  return (
    <SectionPanel title="Cover" accent="cover" blurb="Company, period, and score summary. Click any score for its source.">
      <div className="rounded-2xl p-10 text-center" style={{
        background: 'linear-gradient(180deg, rgba(15,212,160,0.08), rgba(74,158,255,0.04))',
        border: '1px solid var(--border)',
      }}>
        <div className="text-3xl font-bold mb-2" style={{ color: CHART_COLORS.teal, fontFamily: 'var(--font-dm-serif)' }}>{company}</div>
        <div className="text-base mb-1" style={{ color: 'var(--text2)' }}>Management Information System Report</div>
        <div className="text-xs mb-8" style={{ color: 'var(--text3)' }}>{period} · {sector ?? 'No sector selected'}</div>

        <div className="grid grid-cols-3 gap-4 max-w-2xl mx-auto mb-6">
          <ScoreCircle value={out.readiness.l1Score}
            label="Books Health (L1)" color={CHART_COLORS.blue}
            hint="Open Account Health dashboard"
            onClick={goToBooks} />
          <ScoreCircle value={`${Math.round(out.readiness.readinessPct * 100)}%`}
            label="MIS Readiness" color={CHART_COLORS.amber}
            hint="Open MIS Analysis (readiness breakdown)"
            onClick={goToAnalysis} />
          <ScoreCircle value={out.readiness.misScore}
            label="MIS Score" color={CHART_COLORS.teal}
            highlight
            hint="Open MIS Analysis (score + gap list)"
            onClick={goToAnalysis} />
        </div>

        <div className="flex flex-wrap justify-center gap-2 mb-4">
          <Tag color={CHART_COLORS.green}>Auto-computed: {counts.auto}</Tag>
          <Tag color={CHART_COLORS.amber}>Partial: {counts.partial}</Tag>
          <Tag color={CHART_COLORS.coral}>Manual inputs: {counts.manual}</Tag>
          <Tag color={CHART_COLORS.red}>New XML needed: {counts['new-xml']}</Tag>
        </div>

        <div className="text-[11px] mt-6 leading-relaxed" style={{ color: 'var(--text3)' }}>
          Generated by AccountingIQ — all data processed in-session only · DPDPA 2023 compliant<br />
          Every figure is deterministic and traceable in the Backup Working tab.
        </div>
      </div>
    </SectionPanel>
  );
}

function ScoreCircle({ value, label, color, highlight, onClick, hint }: {
  value: string | number;
  label: string;
  color: string;
  highlight?: boolean;
  onClick?: () => void;
  hint?: string;
}) {
  return (
    <div
      className="rounded-2xl p-6 border-2 group transition-all"
      style={{
        borderColor: highlight ? color : 'var(--border)',
        background: highlight ? `${color}15` : 'var(--bg2)',
        cursor: onClick ? 'pointer' : 'default',
      }}
      onClick={onClick}
      title={hint}
    >
      <div className="text-4xl font-bold tabular-nums" style={{ color }}>{value}</div>
      <div className="text-[10px] uppercase tracking-wide mt-2" style={{ color: 'var(--text3)' }}>{label}</div>
      {onClick && (
        <div className="text-[10px] mt-2 opacity-0 group-hover:opacity-100 transition-opacity" style={{ color }}>
          {hint?.startsWith('Open') ? hint.replace('Open ', '') + ' →' : 'View →'}
        </div>
      )}
    </div>
  );
}

function Tag({ children, color }: { children: React.ReactNode; color: string }) {
  return <span className="px-3 py-1 rounded-full text-[10px] font-semibold" style={{ background: `${color}22`, color }}>{children}</span>;
}
